// 자동 생성 파일. 직접 수정하지 않는다. (yarn generate:tokens)
// 출처: design-tokens/light.tokens.json, dark.tokens.json (Figma Variables > Semantic)

/** 디자인 토큰 목록. 값은 라이트 / 다크 테마의 CSS 색 */
export const DESIGN_TOKENS = [
  {
    name: 'SNUTT/red',
    cssVariable: '--color-snutt-red',
    light: '#e54459',
    dark: '#d95f71',
  },
  {
    name: 'SNUTT/orange',
    cssVariable: '--color-snutt-orange',
    light: '#f58d3d',
    dark: '#df6e3c',
  },
  {
    name: 'SNUTT/yellow',
    cssVariable: '--color-snutt-yellow',
    light: '#fac42d',
    dark: '#ecb721',
  },
  {
    name: 'SNUTT/lime',
    cssVariable: '--color-snutt-lime',
    light: '#a6d930',
    dark: '#95b03e',
  },
  {
    name: 'SNUTT/green',
    cssVariable: '--color-snutt-green',
    light: '#2bc267',
    dark: '#95b03e',
  },
  {
    name: 'SNUTT/mint',
    cssVariable: '--color-snutt-mint',
    light: '#1bd0c8',
    dark: '#58c1b7',
  },
  {
    name: 'SNUTT/blue',
    cssVariable: '--color-snutt-blue',
    light: '#1d99e8',
    dark: '#5ba0d7',
  },
  {
    name: 'SNUTT/purple',
    cssVariable: '--color-snutt-purple',
    light: '#af56b3',
    dark: '#af56b3',
  },
  {
    name: 'SNUTT/navy',
    cssVariable: '--color-snutt-navy',
    light: '#4f48c4',
    dark: '#4f48c4',
  },
  {
    name: 'SNUTT/darkMint2',
    cssVariable: '--color-snutt-dark-mint2',
    light: '#1ca6a0',
    dark: '#1ca6a0',
  },
  {
    name: 'SNUTT/darkMint1',
    cssVariable: '--color-snutt-dark-mint1',
    light: '#00b8b0',
    dark: '#00b8b0',
  },
  {
    name: 'SNUTT/milkMint',
    cssVariable: '--color-snutt-milk-mint',
    light: '#b2f6f3',
    dark: '#b2f6f3',
  },
  {
    name: 'Text/Normal',
    cssVariable: '--text-color-normal',
    light: '#000000',
    dark: '#ffffff',
  },
  {
    name: 'Text/Plain',
    cssVariable: '--text-color-plain',
    light: '#505050',
    dark: '#ffffff',
  },
  {
    name: 'Text/Assistive',
    cssVariable: '--text-color-assistive',
    light: '#c4c4c4',
    dark: '#777777',
  },
  {
    name: 'Text/onBG',
    cssVariable: '--text-color-on-bg',
    light: '#ffffff',
    dark: '#ffffff',
  },
  {
    name: 'Text/alternative',
    cssVariable: '--text-color-alternative',
    light: '#8a898e',
    dark: '#b3b3b3',
  },
  {
    name: 'Text/med',
    cssVariable: '--text-color-med',
    light: '#a6a6a6',
    dark: '#8a898e',
  },
  {
    name: 'Icon/Normal',
    cssVariable: '--color-icon-normal',
    light: '#000000',
    dark: '#ffffff',
  },
  {
    name: 'Icon/onItem',
    cssVariable: '--color-icon-on-item',
    light: '#ffffff',
    dark: '#000000',
  },
  {
    name: 'Background/Normal',
    cssVariable: '--background-color-normal',
    light: '#ffffff',
    dark: '#222222',
  },
  {
    name: 'Background/deem',
    cssVariable: '--background-color-deem',
    light: 'rgb(0 0 0 / 20%)',
    dark: 'rgb(0 0 0 / 20%)',
  },
  {
    name: 'Background/light',
    cssVariable: '--background-color-light',
    light: '#f7f7f7',
    dark: '#2b2b2b',
  },
  {
    name: 'Background/lightField',
    cssVariable: '--background-color-light-field',
    light: '#f2f2f2',
    dark: '#3c3c3c',
  },
  {
    name: 'Line/divider',
    cssVariable: '--color-line-divider',
    light: '#c4c4c4',
    dark: '#505050',
  },
  {
    name: 'Line/cellBorder',
    cssVariable: '--color-line-cell-border',
    light: 'rgb(0 0 0 / 10%)',
    dark: 'rgb(0 0 0 / 10%)',
  },
  {
    name: 'Line/light',
    cssVariable: '--color-line-light',
    light: '#ebebed',
    dark: '#3c3c3c',
  },
  {
    name: 'Line/lightest',
    cssVariable: '--color-line-lightest',
    light: '#f5f5f5',
    dark: 'rgb(60 60 60 / 60%)',
  },
  {
    name: 'Line/border',
    cssVariable: '--color-line-border',
    light: '#e4e4e5',
    dark: '#3c3c3c',
  },
  {
    name: 'Line/disabled',
    cssVariable: '--color-line-disabled',
    light: '#dcdcde',
    dark: '#3c3c3c',
  },
  {
    name: 'Line/lightField',
    cssVariable: '--color-line-light-field',
    light: '#f2f2f2',
    dark: '#333333',
  },
  {
    name: 'Line/dividerStrong',
    cssVariable: '--color-line-divider-strong',
    light: '#a6a6a6',
    dark: '#777777',
  },
  {
    name: 'special/warning',
    cssVariable: '--color-warning',
    light: '#ed6c58',
    dark: '#ed6c58',
  },
] as const;
