import { Color } from '../entities/color';
import { ColorService } from '../usecases/colorService';

export const createColorService = (): ColorService => {
  return {
    getColorPalette: (theme: 'light' | 'dark', timetableTheme: number) => {
      const colorPalettesByTheme: Record<'light' | 'dark', Color[][]> = {
        light: [
          [
            { fg: '#ffffff', bg: '#ffffff' },
            { fg: '#ffffff', bg: '#f58d3d' },
            { fg: '#ffffff', bg: '#fac52d' },
            { fg: '#ffffff', bg: '#a6d930' },
            { fg: '#ffffff', bg: '#2bc366' },
            { fg: '#ffffff', bg: '#1bd0c9' },
            { fg: '#ffffff', bg: '#1d99e9' },
            { fg: '#ffffff', bg: '#4f48c4' },
            { fg: '#ffffff', bg: '#af56b3' },
          ],
          [
            { fg: '#ffffff', bg: '#B82E31' },
            { fg: '#ffffff', bg: '#DB701C' },
            { fg: '#ffffff', bg: '#EAA32A' },
            { fg: '#ffffff', bg: '#C6C013' },
            { fg: '#ffffff', bg: '#3A856E' },
            { fg: '#ffffff', bg: '#19B2AC' },
            { fg: '#ffffff', bg: '#3994CE' },
            { fg: '#ffffff', bg: '#3F3A9C' },
            { fg: '#ffffff', bg: '#924396' },
          ],
          [
            { fg: '#ffffff', bg: '#F0652A' },
            { fg: '#ffffff', bg: '#F5AD3E' },
            { fg: '#ffffff', bg: '#998F36' },
            { fg: '#ffffff', bg: '#89C291' },
            { fg: '#ffffff', bg: '#266F55' },
            { fg: '#ffffff', bg: '#13808F' },
            { fg: '#ffffff', bg: '#366689' },
            { fg: '#ffffff', bg: '#432920' },
            { fg: '#ffffff', bg: '#D82F3D' },
          ],
          [
            { fg: '#ffffff', bg: '#FD79A8' },
            { fg: '#ffffff', bg: '#FEC9DD' },
            { fg: '#ffffff', bg: '#FEB0CC' },
            { fg: '#ffffff', bg: '#FE93BF' },
            { fg: '#ffffff', bg: '#E9B1D0' },
            { fg: '#ffffff', bg: '#C67D97' },
            { fg: '#ffffff', bg: '#BB8EA7' },
            { fg: '#ffffff', bg: '#BDB4BF' },
            { fg: '#ffffff', bg: '#E16597' },
          ],
          [
            { fg: '#ffffff', bg: '#AABDCF' },
            { fg: '#ffffff', bg: '#C0E9E8' },
            { fg: '#ffffff', bg: '#66B6CA' },
            { fg: '#ffffff', bg: '#015F95' },
            { fg: '#ffffff', bg: '#A8D0DB' },
            { fg: '#ffffff', bg: '#458ED0' },
            { fg: '#ffffff', bg: '#62A9D1' },
            { fg: '#ffffff', bg: '#20363D' },
            { fg: '#ffffff', bg: '#6D8A96' },
          ],
          [
            { fg: '#ffffff', bg: '#4FBEAA' },
            { fg: '#ffffff', bg: '#9FC1A4' },
            { fg: '#ffffff', bg: '#5A8173' },
            { fg: '#ffffff', bg: '#84AEB1' },
            { fg: '#ffffff', bg: '#266F55' },
            { fg: '#ffffff', bg: '#D0E0C4' },
            { fg: '#ffffff', bg: '#59886D' },
            { fg: '#ffffff', bg: '#476060' },
            { fg: '#ffffff', bg: '#3D7068' },
          ],
        ],
        dark: [
          [
            { fg: '#ffffff', bg: '#ffffff' },
            { fg: '#ffffff', bg: '#DF6E3C' },
            { fg: '#ffffff', bg: '#E68937' },
            { fg: '#ffffff', bg: '#95B03E' },
            { fg: '#ffffff', bg: '#419343' },
            { fg: '#ffffff', bg: '#5BA0D7' },
            { fg: '#ffffff', bg: '#58C1B7' },
            { fg: '#ffffff', bg: '#3E35A7' },
            { fg: '#ffffff', bg: '#783891' },
          ],
          [
            { fg: '#ffffff', bg: '#A93A36' },
            { fg: '#ffffff', bg: '#D56738' },
            { fg: '#ffffff', bg: '#CC973F' },
            { fg: '#ffffff', bg: '#A0942F' },
            { fg: '#ffffff', bg: '#4E8370' },
            { fg: '#ffffff', bg: '#29625A' },
            { fg: '#ffffff', bg: '#4171A2' },
            { fg: '#ffffff', bg: '#4F48C4' },
            { fg: '#ffffff', bg: '#783891' },
          ],
          [
            { fg: '#ffffff', bg: '#BB592F' },
            { fg: '#ffffff', bg: '#E08B45' },
            { fg: '#ffffff', bg: '#B4B194' },
            { fg: '#ffffff', bg: '#5B967C' },
            { fg: '#ffffff', bg: '#266F55' },
            { fg: '#ffffff', bg: '#13808F' },
            { fg: '#ffffff', bg: '#426586' },
            { fg: '#ffffff', bg: '#5C4335' },
            { fg: '#ffffff', bg: '#AD2F31' },
          ],
          [
            { fg: '#ffffff', bg: '#A43C58' },
            { fg: '#ffffff', bg: '#7C164F' },
            { fg: '#ffffff', bg: '#99446E' },
            { fg: '#ffffff', bg: '#A77085' },
            { fg: '#ffffff', bg: '#B290B8' },
            { fg: '#ffffff', bg: '#BDB4BF' },
            { fg: '#ffffff', bg: '#BB8EA7' },
            { fg: '#ffffff', bg: '#736C75' },
            { fg: '#ffffff', bg: '#C76F92' },
          ],
          [
            { fg: '#ffffff', bg: '#014D79' },
            { fg: '#ffffff', bg: '#788DA4' },
            { fg: '#ffffff', bg: '#AEC1C9' },
            { fg: '#ffffff', bg: '#48595B' },
            { fg: '#ffffff', bg: '#1C6C8E' },
            { fg: '#ffffff', bg: '#64909C' },
            { fg: '#ffffff', bg: '#88B1C6' },
            { fg: '#ffffff', bg: '#44576B' },
            { fg: '#ffffff', bg: '#757C80' },
          ],
          [
            { fg: '#ffffff', bg: '#2D5A45' },
            { fg: '#ffffff', bg: '#429587' },
            { fg: '#ffffff', bg: '#86A99A' },
            { fg: '#ffffff', bg: '#597B6A' },
            { fg: '#ffffff', bg: '#42635B' },
            { fg: '#ffffff', bg: '#586C5D' },
            { fg: '#ffffff', bg: '#324845' },
            { fg: '#ffffff', bg: '#AAB6B1' },
            { fg: '#ffffff', bg: '#747877' },
          ],
        ],
      };

      const colorPalattes = colorPalettesByTheme[theme];
      const totalCount = colorPalattes.length;

      return colorPalattes[timetableTheme % totalCount]!;
    },
  };
};
