export enum Asset {
  GUIDE_LIGHT_1 = 'GUIDE_LIGHT_1',
  GUIDE_LIGHT_2 = 'GUIDE_LIGHT_2',
  GUIDE_LIGHT_3 = 'GUIDE_LIGHT_3',
  GUIDE_LIGHT_4 = 'GUIDE_LIGHT_4',
  GUIDE_LIGHT_5 = 'GUIDE_LIGHT_5',
  GUIDE_DARK_1 = 'GUIDE_DARK_1',
  GUIDE_DARK_2 = 'GUIDE_DARK_2',
  GUIDE_DARK_3 = 'GUIDE_DARK_3',
  GUIDE_DARK_4 = 'GUIDE_DARK_4',
  GUIDE_DARK_5 = 'GUIDE_DARK_5',
}
