name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: friends

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn tsc
