name: deploy-snutt-theme-market-dev

on:
  push:
    tags:
      - theme-market-dev-*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_NUMBER: ${{ github.run_number }}
      ECR_REGISTRY: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com
      ECR_REPOSITORY: snutt-dev/snutt-theme-market
    environment: dev
    defaults:
      run:
        working-directory: ./apps/theme-market

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker Build, tag, and push image to ECR
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --build-arg APP_ENV=dev \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
