name: deploy-snutt-theme-market-dev

on:
  push:
    tags:
      - theme-market-dev-*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./apps/theme-market

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build & Export
        run: |
          yarn install \
            yarn build

      - name: Deploy to S3 and Invalidate Cloudfront
        id: deploy-s3
        env:
          AWS_S3_BUCKET: ${{ secrets.SNUTT_THEME_MARKET_S3_BUCKET }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.SNUTT_THEME_MARKET_CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync ./dist s3://$AWS_S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
