name: deploy-prod

on:
  push:
    tags:
      - prod-*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build & Export
        run: |
          yarn install
          cp .env.prod .env.production
          VITE_API_KEY=${{ secrets.API_KEY }} \
          VITE_TRUFFLE_API_KEY=${{ secrets.TRUFFLE_API_KEY }} \
          VITE_GIT_SHA=$(git rev-parse HEAD) \
          VITE_GIT_TAG=$(git describe --tags) \
            yarn build

      - name: Deploy to S3 and Invalidate Cloudfront
        id: deploy-s3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD }}
        run: |
          aws s3 sync ./dist s3://$AWS_S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

